---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-exporter-credentials
  namespace: tobehealthy
spec:
  encryptedData:
    MYSQLD_EXPORTER_PASSWORD: AgAWNiybEXlKdVk0xAVVbFjUEcon65Wa26X73bicDhkGaeC6ktiQuVjOXDZukZMwv2rADtSzw/lF+qhirUWB1Edflk7QNsKHy/k23W4CfsKe9DJNnZoN/YWkzrvlhgeVxMZt2DlvOrLAPZM71rvKCJs5DyB1/K9gwheEaP6gci11pN8H1cODV4+4UL0GYK6xnXGzhK3A3qX80USM1u9pbZV4Xmlw3P45dpz6+dBF86lm4vONpvYMqa1wyovpVeiHc17nswhlTFySk1Uj3g4vKpGSWtg4oJNdDsJpX0TxskNKxLDMDYsCoRYU6SjlcAfGwP3p/1nz91/ZwvTYDuA12LCp97Z4RHKoBJpVtR/RjPJJApSTcPMQTKuHakJHtKBiknymXg8Hck+o0o9EbK7b3uinGD4xmOzU3gKRBuY7DDrfJ5mRl0G7auHawWb0L2wQVJ/2Yx34Ma/T2boi4ANKQlVypCsndKRoRpJM4FjZHlbmvy+7ZLwaJLPq+F95noP6n3QPBd30XHkWOHuPrxCaTM9VzkUMLC9DyscdnxnY0QI6P/7IM78r94e2o9t1Vdo96DXWIBCP5lIVNFSIjpIhjG3oTaDB7pIrTC7qDSgmNUTu8pCxivQrVSxim+6sjL9b/VrEo8pV8YtLJ9MqWe2FhcBUIubEhTMI20PzbI+LtMslOhHRVupoRRlpZW6IlNOoK0WZ6Rqaw65LIu4Wpa12IsRYOa66DgO4SZEcmay47hNNSA==
  template:
    metadata:
      name: mysql-exporter-credentials
      namespace: tobehealthy
