apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 05-postgres.yaml
  - 10-backend.yaml
  - 30-ingress.yaml
  - resource-policy.yaml
  - secrets/malitda-azure.sealed.json
  - secrets/malitda-gemini.sealed.json
  - secrets/malitda-postgres.sealed.json
images:
  - name: malitda/backend
    newName: ghcr.io/malitda/malitda-backend
    digest: sha256:3be3989586c817b21b753208a2a1d89645a56b787d90c0701d8e697e4a4d7855
