apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 05-postgres.yaml
  - 06-postgres-exporter.yaml
  - 07-servicemonitor.yaml
  - 10-backend.yaml
  - 30-ingress.yaml
  - resource-policy.yaml
  - secrets/malitda-azure.sealed.json
  - secrets/malitda-gemini.sealed.json
  - secrets/malitda-postgres.sealed.json
images:
  - name: malitda/backend
    newName: ghcr.io/malitda/malitda-backend
    digest: sha256:7117743cc0afea40d2cafcd2b0db8708ffafb05ea61eb0aab183b2132e473015
