apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 20-frontend.yaml
  - secrets/ghcr-pull.sealed.json
images:
  - name: malitda/frontend
    newName: ghcr.io/malitda/malitda-web
    digest: sha256:2a7a4e76a03dda3fef54322f1e706ede81f381733ee195b8e2319557aa4403e0
