apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 20-frontend.yaml
images:
  - name: malitda/frontend
    newName: ghcr.io/malitda/malitda-frontend
    digest: sha256:35e2a159232d2e9e748ef904eaea93260e34a8d9b2eadbaad2d122b2af731311
