---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAHkjapFuweOxRWHrlXrtAZW7lgt/gUF4ICuAMfaabmfArZK6/eCfEOMZHTgrCM3jrfPpYqBAKdU9kSkXtx92me4ineUHHUv7i8bRG1yf01o8oEGSrVbAcSi30bpl1f/Ev7Per5+sfbp8Bie1bwpy2oYBAMUkHtz/MzXmAZfACOZx2/zBlM2+C3njdiqZz6igsBkH8MhWSOElOWB6JlLtPykuaVQoL7ljoHuYLE3uEdQhf9lvixx4sYo39VXSARuA2MIaPJIMasJs7TcTep9GbML4uBg6X5jIaiu4hjv4xxLDS4DtB17mqJxBacgcDSZzh8c0ov/1cx2BhGsMyiKP95l93tCklTePQ4NzfaDS4OsPM5uOuu/L9LiZUMCZr/lGNZV4QgTBTn5T257Tnf8MnLfG9gLJHAgq8xRZ+m7cJIoBQnpHegsP53nVLlT6ljf3nA/QwEgiBoCTlImMz05ZYyy3Zsk/RD6bF2fyFRYm7oAVhgM/2kA9aYpGM+8C3ok+MWXRcGYUZRykzRJD4NgDEh+khXvCAPkP+aQbFAku4sfWh6lareGjaCo/KA29YynWaQsz9zXoQ+A2LJ8nfEOzKRinKwNdygQvE8EN5pXqCBPJfKamGSgvtf0FcNLjaHV/QHWSu2besp86q7kSniEeU1pDKSPVPbItQhMwpA22MCRHhpLcdCk9Ro2TvUtoMGhppujj9Am2OzqBkrAi3f4sFGDIsE6/siv1skDZkx
    admin-user: AgBax4ZzHUTpFYnudxqGUTYfFEK99UHraPpEe2bgRb7DHemykmzRsFoMFkaIM58PZfMiEYmS+ayS3kNg7p4OfUJfU0EDXk0nMwYvJXRg6STro3A5KZSi5SFdMBcdWOfqoXv9OIqFu1rdt+PCw4S31245rHDq7gJm3oYxhx0rVe+t014+DLeAQg4JWWu6JJk/IOgQtGdzYk2DS5axu3s38yz30TBtWOOmXDB9gqQijUIJQWGQhQW3i3enWdAUNzgbLNDcfmnlrTqyFPNXwwYJNi3ltj2QlhzFP/94JicC/QnEDv+3r3kVHW1yPDP/k20Nkz46s52PMV3v4mjo4X3A82Fqpt43f5MkYSBhieWevmOUAdoNe+gOLIXqrf0HLwVHGWNJIEDO3vVLfr9oRmCXA+4y0eBzH8q9WgQtWMkY1L6xkodkqR6DDYwmfzStu5iYcTeqCTaRNiqF+CpsjkgTkEZn22AJdpz4DI0x6rbFmktKtrRFwShF1AavmvMUMEGTPgfqnl7h9GlBZ+ZT27KJl56vOZMY7yQ9XDesRbJTL3AbeqZscr4PMv8zuDY0QA/UeZTGwk7dbLg5Tku4su73W+pqyS6XMHrpRvpimfcWJrRKAtaW4GWE7gBqORbU/+wIzp4gftc8/RdJdigrzFsTku6LFhWFVHLBqyHfozhTuJ6X0Lm0VdvLPK4JKaM+t5Ugpd8Ka54m4w==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
