---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-aws-secret
  namespace: geonganghaegym
spec:
  encryptedData:
    AWS_S3_ACCESS_KEY: AgAJu7U4RZLQnTVG9zJ8wfqBpm1bsLkZ59ERLCqup+ITwIFxwWk3svHfUM9KT7QIdog/7V0g2RKiSNoWN/tdMk1G6NCxFKizpqlBC/IDvII40HXY0o8t2nVNO9WXj9t35rSbJj9xzUnLtklaazqXFDUzZ7YW4a9KBJDoG8pTECh6e5UOEmajzgoj7mLDyeycajjqlAdtgZwhg34t3q0pYs1DHK1wokGfmyYuqr7vPV8f+AZrQF+et+2N5Y72ZUW6ioJV2Sx3nAFlcMlcLnxTH5NGslcqj112JIQirM3iTfZqruMV7YwHEfLv89AzKu6LPhRRWIJ+4fNIcxihXU9hdfNW5tqXrKOSv3RNlHJnEtF+CtJXd3K8TNS/AIrerG9e3QNj/p5Z4ShF9bRHQ+HWoQxMYM+TrsSzYiaEeuQWE1xIa4Cs5P9R7Inf7+AfCvQlBdoxnSkacYtojmgWeIaW4EchbkqO0PKf6A8JYTnA+CQrFH5BjqWg6eD3irXCJSVCIWabL9jSFdYlFzo2nL6hpwL38vt3/rxcaX6Js/tLquPr6Ep6mHTLzLAQzWoomDbZLNI1C3fMzSJh/5gygCk8abz18HGZz7zWJ9A8+3c8ahpM6SOTlX5w+38hExPXNSrM2MvhLYjloY54ZsCy5Qn/59tI4u/5Nptca/wGS/QQByVhD3DsWvN2FrYGF0ElF+vYBDrpm+yvKuIgXcyTqNZ5+hJ9XZSewQ==
    AWS_S3_SECRET_KEY: AgBQHbkaSutJE+ertiQcvWklypmk5nTTNFfRTdAsRKTCsVdacKtAPuvQH4a6/3uReZXes5QrUrWc7kXM3LooqaGkNfthhzwmnjoI/D2s/ObqjdoV1pkw+/c3JSQFasy8BA4azViCyTT0+l9LBopzV9uN+mODqOM6I8qaj71djQz18WHTLxwpAXr7/N0aYUyb4xqp0Ad1mVNO4k79+fTcqum/YjXOaQrDcGkOOI9qhv32h7mtraz5q9TX8FxuIX1fIWZIt2b1RjNiL9x6PZ2WFV2VO2q5TADio35lKCwDRepoP0ii0igZvNXaL4/xbAV53v3zNBTN048rxA/8SEYgM8ErrJAyRErGuCzoexJpePd7jNncLPZavf13SGl6GzN9gy2qij4y1bNq6G0M3leRhtU3Q112iDmqKUilFzsHKxYr2M5hNn/l9sB+xZVuNJmeBVymVqBEh/2KgZ6LnnV1mH+eD7/QedWnk2OTGpw6Giy6WWjeDKGSb/Mh6bK2DlPUpGLQCJ2df8pu351uv0ApeXs2tXMjiOLSxH4CyiG1au6jTwhdsn+2FMfaUKsdU7zCNhMlRc46RJ/tRIHsTbsoAYwHkEhChcgdd1oA1dvDnol5EYTWLQFuZvGzXC4f4HVjEfC3wq11lvHOsOgIKKcskDzwETeDrj+z1KJjPWCrkUAEGGbMxHzRiOaIxHZ+7R8/Ik47v1vfaQAi0paOW2xAhM3tpf350vn653dFYnISWi4MZc48cyPXR5TU
  template:
    metadata:
      name: backend-aws-secret
      namespace: geonganghaegym
    type: Opaque
