---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-redis-secret
  namespace: geonganghaegym
spec:
  encryptedData:
    DATA_REDIS_PASSWORD: AgCV3wFJvHwzQ0iwjghoz45YWcfTiKOCAIXtAdtWR4qhCLFVm1oF65qZc0UEZltdJUCPTDF1ylkROylUKxHaE35+WpNhnFb9z7OmMV57x1nuJoSKYldXWWLwQdeQsQ+s457KjNC6ztcTypmmD83jikYR/4Lj0tYzLLPkeWLzG0neO0bvIaqZlJKTaFvrNDlgJK4tZ3JWSDtfZAzG9zcW59IkMw5mBh+bAWlBxZToPnX295zQgpYUCCfJusPvJr80MYImbadbv+ILK2HEOLqFtTBVRMyhCjwp2e6KcCUNYT9mqY8mJydTkjfJWk7bnXMkSGJKvyPOhqvOsBrZyqg1fFvqRW//vRK4VgAf4Z7aZRsPDNhTZ8/RKF+uwyex8oWmvWYNdUrhFC2AL9qiGR/TfE2HSVzmp915UjPVuRuIqCjqUfTRioGpEtPoBAjwpA+CDeV7gC5NpZnxMhZa4+btajw26Td4HCzGOKScItHkJhEBMTk3F8Q6/lJtvZz3M34Io57rrS9LLQzrrXfhMh57sArdiv02uUD6/ERR7vvq+byALdWsWb6HXIh6ibOnVpkkDDeZW3w1YVA8DcBjH/qqaHC6aJT0hs3jqd833vdnLnH0m3DPk5sqjeE7RXuuohk0nrMl7skqa7Cjpi8rjkRuiogRil91mko7rENXxJV0Vw5XMDKUhd0tsFlWz5QnLloDWxQwPdWvhqVnj/iRVcdXJf17Zp9vbVrIvyfjtzQdvvHtHg==
  template:
    metadata:
      name: backend-redis-secret
      namespace: geonganghaegym
    type: Opaque
