---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-mail-secret
  namespace: geonganghaegym
spec:
  encryptedData:
    MAIL_PASSWORD: AgAWW9mRsMuXKeiuq1hVG+RKbqdxIs0ouLjOW8zgYpEoWslmLZAAwdwZpYFnpnFGBdeL3SxjkIsh5UqO8w95ku9cTcoYIHMYQQHzmi2EWNlC0W2cf73Wv/9kKY4IYqN8a1G71TA+xvVGZ08lWxqlthDH1lGUClqvnEhmdFfDv6A6sWc0hOxU3M8olHaOpc3bf5Wnc/8RUC3+n76Ad2so0IunB3FL4JrEpDFujW0kbNYrdb5HJhvgOiW/cHiRrWRPNUCYAhXHJ9kE11stuIZ7SI2Y0X3QOfCRuvvRlzSJ+OERXWhgW55c76sNZz/aUXpevX03cd74oIdANMctJkEA5BKGYroNkx8AlLBf/9tcTLDWcTomZa1/PQY7O9CyL7pm1ZQdcL1hGGaXRO1eKVVsOq7h3AA8DtEGVFLWGYOOL4JC/D2Oj5WibllKGTu95pKVZ14ZfexGRwzA8TTjdnYtrM4WPBTl5y29d8ovn9ViGFvT8c0gZuh9JdVhwswC2a4FW7L2V9wfeulUa6pAzVSa+/JyeAs+VvXRedEnw1nPZPUPzw6/Y/hJIsf64Akccbrzy5zXtuMC/yWjTbG2A4HMOyHCFE3Zkv/LAPxyWweZVd3wJN8ygl2X8pJp0QG44nohiKDr6GceevGdpgTyfbbXShbJOGgW8e6VkGezYz4Hairbl1jL4J1cbCOFKu5LPEcgfCv37WXdcBapHmeA/4ePyH7A
    MAIL_USERNAME: AgBGAg2D7QM8DPM/jiWnI4NL/FT0+lTg0bQA7Q227MEK+aD2DFLsNq+eul/a/UuQvUCb8bVgFTy/65DmlqEbXWvmxL0DKqxxon9Lb2EovTz4G4mv2jp93fqRWoXLYa8Tk5lGw1tU0UFoQhwo4DfLdPZElHhVJ7hDxDVBMb+khSNjy1UuknZo5mIwlW9Lrdfwu8RI66+eqt4gS/zzAdWdDNU6V/6fpdoZPPtC2WlVoHON4/gn70Y54FARHZHBiqBBvde2cnxPxjAD9nC9Y/PCjT5jaBhPshB5u0DNIiIrBmofR1M5fNEeNYotRqIhfFRa9R8OI3a2yVFNLPawIglNC7z+oOKNGxN2g1vvQ8+1MTk42oTtD5h4cO3DBksmJY2SQM7HsG5q04WqsMpwK7N8xyEPNzp6u2IMkK2jLMy0V46WQsM5bSaajm1fPHc0zlrIdsgp4PJSFVI2zvYG0S8lJWQlWB4qJQCxr5H6/eZpLyk5mxX1+EgHBbqtQKdxOKerK6T8l0e4F9lRwHOXCjqbcvi2J4JY07CnXriNuRAK2MqUMzf7ObxRQdZklwij2QccEfaJmVOoIeLrZaXooXd75rT5jGgho3e8keCOdloQD//fO6qq9qSIe3jbhxLWsK80DcmWNP6+9J3EG89VvDG7gg/koScEpCKLpqw1EE7ocJ0lUppOiGS6oo7tk9TGU3iAWTYB3qrSYYVWuHpzdvuVQW8=
  template:
    metadata:
      name: backend-mail-secret
      namespace: geonganghaegym
    type: Opaque
