---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-apple-key
  namespace: geonganghaegym
spec:
  encryptedData:
    AuthKey_YAFMRF359Z.p8: AgAoXjDSqLa/6ytclnA2Mna+XW1v7RhEqxwaMuTmU8o00fWXQD8/A4GXPrJ1Ec8nD78orBQFotoWo6MmiHFZeJ8ga3hj7sp5pTyOrhCumIDQ5rTkbS/5r8qUEx4I/C2JqoM9kCgJEcFp43RhErg2MSH12XmsbOj4MFkJGOdNhaF9ACmNtLAW6XhRFJpXeUg21J+DNdsB/B2rGbdUTiSrmWipqaLpeeD5hgaQsthBYvHX/OvY6GucgTNOOvQDTovOc8MiDlCoDJvGP0bMHyTKAAB8Wb6TGcD/a91h3DjYQXce6amWmue/jUdbCG37jZHPNJMWQM1srAU+SOH6yEW26NQesPHQDw2tS5kw0UcoTzVjGzlsk0xI/1ILl//noNpWq531ubmq/XvupOJHzsG9chmRlQMP1/1xzb/f9PA4c7/EQNP96kmDCZ0TzJixXfapqwsvYVaH1IAMY7kdOmzxDmtCR9oB/+VvTktmP43lZ5ZvhPrBhZhbuRfAU5dG4TpxGYq91atxRsqUO7cVolKS2Rl9Afs6Fb//sjGOYJARwBu8H7x25bdvjsCMvB0xV0XRkoPWQcvEtU2u8U46Rr7hmPV76nrRfxsojppjATlaEBPTQ11c0JXTUhg6iEeBjsh181IQUOGMKyUAHKrmWTe9ge0TzC9e2rbLbL1YlRUzaOGU9w9wS4Vc8TS4uLZuU6WB9NhvBuWQuEZCaY+8JDO6lXchNUnaAmOHBZCHXLXS4SNS3TeVnGz//rd9zuU+kA8vkxXvls8jDCEHRFowXQFIME94SYMNdmhfST3QS/gThsnEnpOgLqDaKQXY6Ca4KGi6+UmUoCY4OGWT+ovZMWA+6yb6Vw634LQLJ9XjQ6J9cNKH6/FbUbjeg4xwrvOzZ3kOTZlNM1y+huDN3rgSidy7+T43aeKzRKDYmvrqYJ3jxXRfqkhXBArzSifnLqbCyb8SAlyKGpXch2KL0ztWasxN8rVbrNGZWfzowIe0c9AviOXQ/jHa76gdqEFkFJBj/q2quqRb3evrN03/X61HMxcPUAtMRw==
  template:
    metadata:
      name: backend-apple-key
      namespace: geonganghaegym
    type: Opaque
