---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-jwt-secret
  namespace: geonganghaegym
spec:
  encryptedData:
    JWT_SECRET_TOKEN: AgAlx2oUibPQv+uvj4UxSXI5XBrWgEAfh5HkQ3F8nIVpnrI0sjlDXL6Do3umjxsMb7dDDo3lVWKckDm9J0Uymo26b8pjLDU1+BNyHIqquiXYMJ2EZyo8U08BC607MGLr+ncK4V8Rsf4425k8boafzEEf5ZVs4isv2GjpcLQ/V3i6tIOWC3+RXqtiqYKguqBUW1n3VzN2egA7gKy8kJzH3uK1+PYtjE9UIzXjFrHEWhKwCMhHhz9Bd0E8/c1n3HWqmbDPqg55XxZPHNEsI7yrGURzPz+Xc8vo0PnI4IRWbDYYAtFg6Qclm/4cTXORP3zp4oe6B9hWmeKSOhMb79d8sBoJ7tVdPqTc/QkqROHlsysmldZWjosFHwznbNrzIcJvIf8nGDeFe3W9tkznwBMhHJ1jlkZClY0mviAwTPV8vwrA9qILP5terPnhi+hzRqcjiY7S3FHkYi1Jqni7LFo9myJJsjgXwxJ+rNbGk3fO79PI2wXz8cwZJC+7pMspQZESl2fUfzMe9pAohV/CF+zF9NvBVX17l1zNI1Ymgsgse4WmhJZcTTvQwLqC+Tv28RTD7cf26nrzfACUrW15k/hWe4TI0QTKibQsYIxEm8fkHxux07swegkxo8jFWlfCUcVDMSVN0EljYYpksFvvpLoteBj2FKA/xkSti0gPW9JoTH64aUsgR2rGpLAcgCSC91Vd+oKktQUMRz+llHa6CopMb7vGbxbxtUn6D41P8Air2JzZ+AaFswTSLziKWhEma45/FS21WrYUbYj5wGFFFHK6Vh+o
  template:
    metadata:
      name: backend-jwt-secret
      namespace: geonganghaegym
    type: Opaque
