---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-env
  namespace: geonganghaegym
spec:
  encryptedData:
    INTERNAL_API_URL: AgBG/rYNX5QIZx7zelt/xPqrMazZvYnw+U7+LBlMLco1pSeadbC9p0beCLpqR2dJtW2eIuhOC0Ri2hoCdlbj4QEnc464IXFVpHK1KWD+kIO/6b1vmyi7NDQpv0++2gQ3gS4DlTjdv7X1lbaqhpax6r5BpCNSCWPE1jj7Fogkz3gACC2NQy1iKr3p72UG48iJMgy+Wh4eNFLZ0iPmz28t7NUsGH7rWefTjoHyMfGMtcQ2KWxNjpp2FVX/hTkGVGe+2VXi1jdNjeeX22pqYhd2xwEziyTittPJWNwGFHGIBewZ2olL1tzASMk7drSjfwKaL1UipZ0uJM4Sz/2cRNcW/sioehNUj5798hOGsg0Rr0L1srk18TmQqyo4L435XpuQnr8YuDvFe94OHcPqFHvbtIgkEhqBHibLqtvcyrCJLP/wbFFW76sKY+dRw74c8jqL8C/bsRVlckt+16FA0pEJ/Jd8Wl0IHzeQSkxZb1SctQgrHWWeOfOQtlY+AZLM0YtQMCoJA9AfZSJmi7aMyh1ZCC2FkAImyK1e/BaFPtRaHakkKPlud3VDxT6L9ji0SsWrir4PmkcfRjPwOHbEr4Jwq27V4tSr35a9RyJYnz0W1kDQIArnPUIZrTKfGeLtylRTtXW11hx3mFV8qXDOUZEGRkOTJW4I73iDbebrJgi30najlVwa2v8qTZQCl3O3a9zUoV9Fwd3IoAV+8OM1qMY9/+ucmyR5
  template:
    metadata:
      name: frontend-env
      namespace: geonganghaegym
    type: Opaque
