---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: geonganghaegym
spec:
  encryptedData:
    .dockerconfigjson: AgATdbJdz60MW3RJlwocMkvRtokxrQDnD3aa38Kw9mM9/Q/YJIfNs6s2mzHF5i+t0NJlV39kRK+z+Sa9OE/r2E/YCSthm6yCw78KxsXD63CrGpPZAKgC9PYteLFwLzuEh44oBs8+iuAB3xbBbEH/fg//69QP5VevD8OIIVZ0uvbDLQNrLxLpBtwE52zT2/uD76Uhv+YzyMzuKXGIJVK0oF1+co9F/1nq9qjjurjXhFkpu+c5w/rpqd93SglWPdLzxuzdTF/7m3tOhTlcg1ZQJkdcaeA6DcajyZRHpIaxvEzTVP25YjFWVR9ili8huurPBX/642vVqwzRqWkgCyG+3PI8DQ3R2Tabt80U//tKYUs3TH4pQUeLCeGlfBWfNrOQjWqfad1AcZrPp+QbQ2mFZZb6kPIbE3ELdlEHaXKJx0JVvktP7BPad5EX8HnWy5SF/s5UdVap+ShfK/0HXoDV2rnOWwrqEcDrwmJcGk3IqRZYgO1zvQtPrNHBX/a2bvchBH7hWr2GL8yp56yZUGoruqMVvoPWXoP8Dfgs2L/XM/Ix51MnPbwe3/0pwylU+PXcfrwgpiTW7RJ68a9M/xAaxmGPn9Us+oVWFTdZ/01FncToSpz6Yx+bLAIVzDD/PJdxotKnBlNt6Q0ugPIAfr+tGnDB0/P+9XOpgB0cBupLUcfEz4RiPzfOq5sAWiSXecODrn6/WS9a91hQMbxeKi1uPMUEPN2W14PJM1/+dSgTseqLsT7cGTi/98u6v00svo+SuGN8K9YYcC+mslsNQjf9fQ2uyvR8oqWtlsMdgVgq9QLR6LkoSc3ZE6fEq63qHieEb8UQFv0/wmhXMBrZ+gt7ZcOvtLSQ940ussjr04SJYW74d7/plzNySJ/fK76+PlP5o1nI/jt1HbdGrLTgTIxgMJu/u+YCs0UGC0gMw3tt46rXMdiXY5aZwJWUNQ==
  template:
    metadata:
      name: ghcr-pull
      namespace: geonganghaegym
    type: kubernetes.io/dockerconfigjson
