---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-exporter-credentials
  namespace: geonganghaegym
spec:
  encryptedData:
    MYSQLD_EXPORTER_PASSWORD: AgAFMrKzbruNBZuU5L8Fs8l/ffEIx+r6gfLqN2lIJDvRNkk9ykUFIN015M83++Bh5qR709ojuIfCtqjG/jA+thg4ZMYYfJH7H0d4gTA3ZvLMFEL+su7tCxymLAybo2vwwwDItheu7lVc2lmwETzt+xDbGB1QtUCKDFIXLpgkRPRCaJYiKYH1VgdE2ffAZ2icoqxUi0eVLWvo2jKf8SIUgdTnF/AUcZOZrL8i2WG4dNeEQT2Rupfl0N1BHFXmOw31jqWlLIWqrlPx25U/Kxt3uFfpRsXDQJvOXEyP/HrnkosU+/LoqC5FLzwvUhivWZO2j2W259XIgFbC+7fKDlAzl/B02o+mbVSlGPtKhLzh4K9A/KX8T2LCL2Thg4+KRrsXZPv1ngb4ekLwRtYV+YSwDQOZZ80e8CVrYqq/d8LgQOVgkaS2EoZhDb1Sht5K7Yw6pqkbNlEQM/DFI/o/4W6Hr0mofdE3ND+T8fK3QUJldCPrZjzwtZFXt5AYHsQPH86VuSQM9hJs4uyVvppTvfW22mj9OhvBZ08KtUwJahAwNBKB8O2g3TzCj/dsu+/9rPNbva6KDm45XG+nsae7c09NMUWPZlDM68ZPy05VgwZun0CYWJfMdPFcefqw16LCppvFon4R0AV1TuojdOBc9/1o64yAegVqhp55C8XqkMq5wangsk5OCYXqW9JAk3CrMb2iJJ1vuNkvQs671B0F0XGlRS9YHQKxqQpV7ThFmzfdr/f2Ig==
  template:
    metadata:
      name: mysql-exporter-credentials
      namespace: geonganghaegym
    type: Opaque
