---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: geonganghaegym
spec:
  encryptedData:
    REDIS_PASSWORD: AgA0X0vru72+O69S9YYfaf6aSwjPNTFvTYlQB7cRBlJH8I1A4FtHLFJ35nLZd8R6VGypbcmNXjZotJ7F9VqZnPAMwJVOiJG+7LykPo7Jdf1BqIfJUa3iqshWAM0Bcj8af7sFu5LVG/Izh5hOVNN6QjyS5JEoF/2ZJbpoAWbO+tkEmUHrPJVlTTHfPAd6pL95PaakDHxd9FDfHpsMVNrO9mJC0wwWub13bGXYaSeciNZ+csFvNAVdfJDzETLU28sO1IEw+rzQAYSFS98XPCo/HrH3qTm+pK4x/krCLwC/oRnv6C03Z9ose7YopKKfUDEUvRugy+fka67ZXin39ugOt4RrSWd1WTZYZ+Qu/jAUuOgm/alSI3KHxWw3XjM8+LuoavvD0kzcqDxih4EJpibQ/sMS5H96zkNZ00PWRNrgpZMYVKPw6ygmN7sDxsnKC9Q9kB2WwfkxJqB0FAXP+tuimE9CbdOoOw9ioqe+0Yx0fG2QjtmMGSfmfu8dPjoNfc+EHBwbuhpMNOhpVE+xrmQlH/LhuirA1LiLQ8hojJ3M95z+sD4dKFs+alR7hPjs42+jHLs4zCbtejjRpXBJVgTYqyzUOY8G+OgU5v3R1LeEVee7S6bbcNVSjphQT1cb+oiwgCRdMCUpUeomaiSHfiLxvep5aw7ZTE0Zlyf4yIs+5iWr6Mmd6U503T3pyR+PI2c24O+ErKL5zFIeV3NWmoe7ahnsj3ahNCQjrfDOvhJA08Ienw==
  template:
    metadata:
      name: redis-credentials
      namespace: geonganghaegym
    type: Opaque
