apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  name: backend-files
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
