apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geonganghaegym

resources:
- https://raw.githubusercontent.com/geonganghaegym/geonganghaegym-web/main/deployment.yaml
- service.yaml

images:
- name: ghcr.io/geonganghaegym/geonganghaegym-web
  newName: ghcr.io/geonganghaegym/geonganghaegym-web
  newTag: sha-05a39e913c31
