apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geonganghaegym

resources:
- https://raw.githubusercontent.com/geonganghaegym/geonganghaegym-landing/main/deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/geonganghaegym/geonganghaegym-landing
  newName: ghcr.io/geonganghaegym/geonganghaegym-landing
  newTag: latest
